apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: jenkinsgit-ingress
spec:
  ingressClassName: public
  rules:
    - host: kimo2007.dnshome.de
      http:
        paths:
          - path: /jenkinsgit
            pathType: Prefix
            backend:
              service:
                name: jenkinsgit-service
                port: 
                 number: 80