apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkinsgit-service
  name: jenkinsgit-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: jenkinsgit
  type: NodePort
